linters:
  enable:
    - godot
    - misspell
    - stylecheck

linters-settings:
  stylecheck:
    go: "1.20.3"
    checks:
      - "all"
      - "ST1*"

issues:
  exclude-use-default: false

output:
  format: colored-line-number

  print-issued-lines: false

  print-linter-name: true